# Generated by Django 5.2.1 on 2025-05-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPost",
            new_name="Blog",
        ),
    ]
