# Generated by Django 5.2.1 on 2025-05-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_blog", "0002_rename_blogpost_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(
                help_text="Введите контент для блоговой записи", verbose_name="Контент"
            ),
        ),
    ]
