# Generated by Django 5.2.1 on 2025-05-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_blog", "0003_alter_blog_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_congratulated",
            field=models.BooleanField(
                default=False, verbose_name="Отправлено поздравительное письмо"
            ),
        ),
    ]
